# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(help_text='Copy this     address and send it to voters who want to participate to this poll', max_length=100)),
                ('admin_url', models.CharField(help_text='Address to     modify the current poll', max_length=100)),
                ('author_name', models.CharField(help_text='Name, firstname or nickname of the author', max_length=100, verbose_name='Author name')),
                ('name', models.CharField(help_text='Global name to present the poll', max_length=200, verbose_name='Poll name')),
                ('description', models.CharField(help_text='Precise description of the poll', max_length=1000, verbose_name='Poll description')),
                ('type', models.CharField(choices=[('P', 'Yes/No poll'), ('B', 'Yes/No/Maybe poll'), ('O', 'One choice poll'), ('V', 'Valuable choice poll')], help_text='Type of the poll:\n     - "Yes/No poll" is the appropriate type for a simple multi-choice poll\n     - "Yes/No/Maybe poll" allows voters to stay undecided\n     - "One choice poll" gives only one option to choose from\n     - "Valuable choice poll" permit users to give a note between 0 to 9 to     different choices\n    ', max_length=1, verbose_name='Type of the poll')),
                ('dated_choices', models.BooleanField(default=False, help_text='Check this option to choose between dates', verbose_name='Choices are dates')),
                ('enddate', models.DateTimeField(blank=True, help_text='Closing date for participating to     the poll', null=True, verbose_name='Closing date')),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False, help_text='Check this     option to make the poll public', verbose_name='Display the poll on main page')),
                ('opened_admin', models.BooleanField(default=False, help_text='Check this option     to open the poll to new choices submitted by users', verbose_name='Allow users to add choices')),
                ('hide_choices', models.BooleanField(default=False, help_text='Check this option to     hide poll results to new users', verbose_name='Hide votes to new voters')),
                ('open', models.BooleanField(default=True, help_text='Uncheck this option to close     the poll/check this option to reopen it', verbose_name='State of the poll')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.Category')),
            ],
        ),
    ]
